name: PY38-TF28
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - matplotlib
  - pillow
  - scikit-learn
  - graphviz
  - pip
  - pip:
      - openpyxl
      - protobuf==3.20
      - ipynb
      - numpy
      - tensorflow==2.8
      - tensorflow-datasets==4.7
      - tensorflow-hub
